Project Regression Models : The Motor Trend Analyst
========================================================

**Questions**
1. "Is an automatic or manual transmission better for MPG”
2. "Quantify the MPG difference between automatic and manual transmissions"

**Executive summary**

Manual transmission appear to give better mpg efficiency in cars tested, yet quantifying the improvement varies significantly with other characteristics of the cars examined. So its better looking around for other characteristics that also play a significant role in mpg efficiency.

**Analysis Method**
1. Explore datasets, to understand variables correlations and approach
2. Fit mutliple models, compare their diagnostics and pick best
3. Compare best model fit.
4. Calculate difference of estimated MPG for these two cases.


**Analysis**

By checking the details of the mtcars dataset, the variable that defines the transmission is "am", a dummyvariable, with values : am   Transmission (0 = automatic, 1 = manual), that for convenience, I will rename to "auto" & "manual" respectively.


PHASE 1 - **EXPLORE**
```{r}
data(mtcars)
mtc<-data.frame(mtcars)
```
First, I will explore correlations in this set to discover which variables are relatively significant variables to include in the model and which aren't
```{ro}
pairs(mtc, panel = panel.smooth, main = "MT Cars", col = 13 + (mtc$am >0))
```
I observe that indeed a few variables are correlated in with each other and with mpg, presenting a monotonous distribution.
Also by coloring the two transmission types, I notice that they are distinct.

Then, I will quantify these correlations of variables to exclude those that are highly correlated with each other
```{ri}
 M<-abs(cor(mtc))
    which(M> 0.9, arr.ind=T)
```
    
Variables disp and cyl have correlation >0.9 so we could use only one of them as a predictor. If I want to select a few more that appear to highly correlated, I lower my threshold to 0.8 :

```{rm} 
which(M> 0.8, arr.ind=T)
```
I notice that the following are the most correlated with the outcome (mpg) : wt,cyl, disp,hp - So if I keep those with best mpg correlation I select : **wt** (and exclude disp) & **cyl** (andxclude hp, vs, disp) &
So finally I conclude to the following variables as my principle components :
wt, cyl, am, gear, drat, qsec, card

PHASE 2 : **FIT DIFFERENT MODELS FOR AM=1**

Let's check what fitting with the above insights yields to. First I convert my dummy variable in a character set, to make my results more easily interpretable.
```{rax} 
mtc$am<-as.character(mtc$am)
mtc$am[mtc$am=="0"]<-"auto"
mtc$am[mtc$am=="1"]<-"manual"
```
Then I fit various models, one generic with all variables and a few incorporating the selections of principal variables I have done before.
```{rx} 
  fit<-lm(formula = mpg ~ .,  data = mtc); f0<-summary(fit)
  fit1<-lm(formula = mpg ~ wt + cyl + am + gear + drat + qsec + carb,  data = mtc) ;f1<-summary(fit1)
  fit2<-lm(formula = mpg ~ wt  + am + gear + drat + qsec + carb,  data = mtc); f2<-summary(fit2)
  fit3<-lm(formula = mpg ~ wt  + am  + drat + qsec + carb,  data = mtc); f3<-summary(fit3)
  fit4<-lm(formula = mpg ~ wt  + am  + drat ,  data = mtc); f4<-summary(fit4)
```
For the above models I check some diagnostics 
```{rz} 
anova(fit1,fit1,fit2, fit3, fit4)
paste("Residuals Variation : f0:", f0$sigma, "f1:" ,f1$sigma,"f2:" , f2$sigma, "f3:" , f3$sigma,"f4:" , f4$sigma) 
summary(fit)$coefficients ; summary(fit3)$coefficients; summary(fit4)$coefficients; 
```
I observe that indeed the model fit3 with the fewest predictors (regressors) is the one with strongest coefficients, and smaller standard error, as well as an minimal residual variation.
This can be visualized by plotting residuals for model all (in red) versus model with fewest significant variables (blue) and the one with fewest variables (signficant or not, green)

```{rb} 
e0 <- resid(fit)
e3 <- resid(fit3)
e4 <- resid(fit4)
par(mfrow = c(1, 3))
plot(mtc$mpg, e0,  
     xlab = "miles per gallon", 
     ylab = "Residuals (Fit all)", 
     bg = "lightblue", 
     col = "black", cex = 2, pch = 21,frame = FALSE)
abline(h = 0, lwd = 2)
for (i in 1 : length(mtc$mpg)) 
lines(c(mtc$mpg[i], mtc$mpg[i]),c(e0[i], 0), col = "red" , lwd = 2)

plot(mtc$mpg, e3,  
     xlab = "miles per gallon", 
     ylab = "Residuals (Fit Less-Is-More)", 
     bg = "lightblue", 
     col = "black", cex = 2, pch = 21,frame = FALSE)
abline(h = 0, lwd = 2)
for (i in 1 : length(mtc$mpg)) 
lines(c(mtc$mpg[i], mtc$mpg[i]),c(e3[i], 0), col = "blue" , lwd = 2)

plot(mtc$mpg, e4,  
     xlab = "miles per gallon", 
     ylab = "Residuals (Fit Skinny)", 
     bg = "lightblue", 
     col = "black", cex = 2, pch = 21,frame = FALSE)
abline(h = 0, lwd = 2)
for (i in 1 : length(mtc$mpg)) 
lines(c(mtc$mpg[i], mtc$mpg[i]),c(e4[i], 0), col = "green" , lwd = 2)

```


PHASE 3 : **CALCULATE CASES**
From the coefficients it occurs that a manual transmission increases the efficiency of miles per gallon by 2.96 with a standard error of 1.6233. So, it appears that the existence of the manual transmission, indeed improves mpg.

PHASE 4 : **Quantify Impact on MPG**

How much better is the manual transmission for mpg? 
With confidence of 97% this is quantified by getting predicted values from our model (fit3)
```{rab} 
sumCoef<-summary(fit3)$coefficients 
sumCoef[1,1]+c(-1,1)*qt(.975,df=fit5$df)*sumCoef[1,2]

```
The results move in the zone of -6.99 to 26.84 which means that there is significant challenge in predicting the change in mpg per transmission type with other variables included. 
If transmission was the only variable, then :

```{rabx} 
fitam<-lm(formula = mpg ~ am,  data = mtc) ;fam<-summary(fitam)
sumCoef<-fam$coefficients 
sumCoef[1,1]+c(-1,1)*qt(.975,df=fitam$df)*sumCoef[1,2]
```
With 97,5% confidence a manual transmission gives 14.85 to 19.44 miles per gallon more than an automatic transmission.
